
spring.datasource.url=jdbc:postgresql://localhost:5432/germes_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.port=8080
spring.application.name=shop-backend


server.error.include-message=always
server.error.include-binding-errors=always

spring.mail.host=${MAIL_HOST:}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS_ENABLE:true}
mail.from=${MAIL_FROM:${MAIL_USERNAME:no-reply@germes74.local}}
# ?? ?????? (?????? ? application.properties) ?????????????????????????????????

# ???????? credentials ?????? (???????? ??? ??????????? ??? ?????)
yookassa.shop-id=1333820
yookassa.secret-key=test_TSexuutu_qM4oNNegkEcFvR2uzGZN5joXd5RJbR62Tk

# URL ???? ?????? ?????? ???????????? ????? ??????
# ?????? ?? ???? ???????? ????? ??? ??????
yookassa.return-url=http://127.0.0.1:5500/front/basket.html

# ?? ??? ????????? ???????? credentials ???????????????????????????????????????
# 1. ????? ?? https://yookassa.ru ? ???????????????
# 2. ? ?????? ????????: ????????? ? ????? API
# 3. ?????? test_shop_id ? test_secret_key ?? ???? ????????
# 4. ??????? ??????: ????????? ? HTTP-??????????? ? URL: https://127.0.0.1:5500/api/payments/webhook
#    ???????: payment.succeeded, payment.canceled
server.error.include-stacktrace=always


